import 'bootstrap/dist/css/bootstrap.min.css';
import "../styles/global.scss"
import { Red_Hat_Display } from 'next/font/google'
import Header from '@/backbones/Header';
import Footer from '@/backbones/Footer';
import Providers from '@/components/providers';


const Red_HAT = Red_Hat_Display({ subsets: ['latin'] })

export const metadata = {
  title: 'Revly',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">   
      <Providers>
          <body className={Red_HAT.className}>
            <div className="body-wrapper">
              <Header/>
              {children}
              <Footer />
            </div>
          </body>
      </Providers>
    </html>
  )
}
